FROM node:18 AS builder
WORKDIR /app
COPY ./frontend /app
COPY ./frontend/.env.frontend /app/.env
ARG REACT_APP_BACKEND_URL
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
