services:
  backend:
    image: alirezaeeali/backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    env_file:
      - backend/.env.backend
    networks:
      - app-network
      
  frontend:
    image: alirezaeeali/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    env_file:
      - frontend/.env.frontend
    networks:
      - app-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - portainer-data:/data
      - /var/run/docker.sock:/var/run/docker.sock
      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  portainer-data:
