name: CICD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  vulnerabilities-scan-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install

      - name: Run npm audit
        run: |
          cd backend
          npm audit --audit-level=critical
        
      - name: Fail on critical vulnerabilities
        if: failure()
        run: |
          echo "Vulnerabilities found in the dependencies!"
          exit 1

  vulnerabilities-scan-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run npm audit
        run: |
          cd backend
          npm audit --audit-level=critical
        
      - name: Fail on critical vulnerabilities
        if: failure()
        run: |
          echo "Vulnerabilities found in the dependencies!"
          exit 1

  build-and-push:
    runs-on: ubuntu-latest
    needs: [vulnerabilities-scan-backend,vulnerabilities-scan-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build --no-cache -t alirezaeeali/frontend:${GITHUB_SHA:0:6} -t alirezaeeali/frontend:latest -f frontend/Dockerfile .
          docker push alirezaeeali/frontend --all-tags

      - name: Build and push backend image
        run: |
          docker build --no-cache -t alirezaeeali/backend:${GITHUB_SHA:0:6} -t alirezaeeali/backend:latest -f backend/Dockerfile .
          docker push alirezaeeali/backend --all-tags
